# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


![numpy](images/numpy.png)

NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
16 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

**Veamos algo de todo esto en python:**


**Arrays**

In [ ]:
%pip install numpy

In [1]:
import numpy as np

In [2]:
# nº aleatorio

np.random.random(1)

array([0.97831861])

In [3]:
type(np.random.random(1))

numpy.ndarray

In [5]:
np.random.random(1)[0]

0.7222923124233386

In [6]:
type(np.random.random(1)[0])    # el 1 es el nº de elemento, el [0] es el indice

numpy.float64

In [7]:
# vector

vector = np.random.random(5)

vector

array([0.76173689, 0.86871302, 0.0436394 , 0.8688453 , 0.13551124])

In [10]:
vector[0:4:2]

array([0.76173689, 0.0436394 ])

In [11]:
for e in vector:
    print(e)

0.7617368905253025
0.8687130227063095
0.04363939827914298
0.8688452989012242
0.13551123781403873


In [12]:
type(vector)

numpy.ndarray

In [13]:
2 * [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
2 * vector

array([1.52347378, 1.73742605, 0.0872788 , 1.7376906 , 0.27102248])

In [17]:
# matriz 

matriz = np.random.random((10, 4))   # 10 filas, 4 columnas

matriz

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642],
       [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
       [0.18579632, 0.19304679, 0.70468915, 0.49778457],
       [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
       [0.97337516, 0.11340629, 0.38642154, 0.93877849],
       [0.27447261, 0.18394873, 0.68564775, 0.33294399],
       [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
       [0.37077889, 0.85323823, 0.92933064, 0.89367351],
       [0.90683985, 0.76705262, 0.30157504, 0.72725307],
       [0.72005348, 0.30712978, 0.35229047, 0.58198273]])

In [18]:
type(matriz)

numpy.ndarray

In [20]:
#help(matriz)

In [22]:
matriz[0]

array([0.05548937, 0.03643071, 0.98093764, 0.49873642])

In [23]:
matriz[0][0]

0.05548937247076824

In [24]:
matriz[0, 0]

0.05548937247076824

In [25]:
matriz[:, 0]    # la primera columna (: todas las filas, 0 es la primera columna)

array([0.05548937, 0.0249585 , 0.18579632, 0.3648863 , 0.97337516,
       0.27447261, 0.98678725, 0.37077889, 0.90683985, 0.72005348])

In [26]:
matriz[0, :]    # la primera columna

array([0.05548937, 0.03643071, 0.98093764, 0.49873642])

**slicing**

los `:` signican todo, es decir, todas las filas. Luego, separado por coma, el 0, primer elemento de cada fila, es decir, la primera columna

In [27]:
# cubo

cubo = np.random.random((3, 3, 2))   # 3 capas, 3 filas, 2 columnas

cubo

array([[[0.72222268, 0.18683648],
        [0.75713545, 0.71349443],
        [0.96680646, 0.9677623 ]],

       [[0.16374711, 0.64822273],
        [0.09125861, 0.07642372],
        [0.14967428, 0.35949459]],

       [[0.01447259, 0.34144573],
        [0.01120438, 0.34370902],
        [0.67437416, 0.16185748]]])

In [28]:
# tensor rango 4

tensor = np.random.random((2, 3, 4, 5))   # 2 cubos, 3 capas, 4 filas, 5 columnas

tensor

array([[[[0.18766144, 0.36546327, 0.64760079, 0.26584676, 0.74349648],
         [0.67493588, 0.16220382, 0.54277244, 0.87870378, 0.14216108],
         [0.93611634, 0.11393771, 0.77543964, 0.996619  , 0.05436754],
         [0.46698682, 0.68624289, 0.52693804, 0.47755302, 0.28200695]],

        [[0.73317751, 0.1853282 , 0.43032689, 0.42485877, 0.33464777],
         [0.73255483, 0.40606555, 0.37969029, 0.56437385, 0.81605267],
         [0.32464736, 0.72766272, 0.33106462, 0.97447419, 0.74413435],
         [0.3498945 , 0.32568609, 0.05532058, 0.69091805, 0.34319538]],

        [[0.72599276, 0.79426046, 0.27343958, 0.11879116, 0.85214072],
         [0.7026108 , 0.92197919, 0.64259516, 0.59671374, 0.49718923],
         [0.28307523, 0.45522329, 0.81074272, 0.91973413, 0.40236751],
         [0.78464779, 0.28994558, 0.21660883, 0.63289317, 0.14563361]]],


       [[[0.60439214, 0.39012504, 0.24775145, 0.64017915, 0.67784209],
         [0.80928414, 0.52907967, 0.56677263, 0.49951623, 0.62143505]

In [29]:
matriz.shape

(10, 4)

In [30]:
tensor.shape

(2, 3, 4, 5)

In [31]:
matriz.size

40

In [32]:
tensor.size

120

In [37]:
tensor[0][0][0][0]

0.18766143878439412

In [38]:
tensor[0, 0, 0, 0]

0.18766143878439412

In [39]:
tensor[0, 0, 0, -1]

0.7434964790457724

**Operaciones matemáticas**

In [40]:
matriz

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642],
       [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
       [0.18579632, 0.19304679, 0.70468915, 0.49778457],
       [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
       [0.97337516, 0.11340629, 0.38642154, 0.93877849],
       [0.27447261, 0.18394873, 0.68564775, 0.33294399],
       [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
       [0.37077889, 0.85323823, 0.92933064, 0.89367351],
       [0.90683985, 0.76705262, 0.30157504, 0.72725307],
       [0.72005348, 0.30712978, 0.35229047, 0.58198273]])

In [41]:
matriz.sum()

21.222923688069542

In [42]:
sum(matriz)

array([4.86343773, 4.36654907, 5.67961945, 6.31331744])

In [43]:
matriz.sum(axis=0)   # suma por columnas

array([4.86343773, 4.36654907, 5.67961945, 6.31331744])

In [44]:
matriz.sum(axis=1)   # suma por filas

array([1.57159414, 1.95979326, 1.58131683, 2.28142237, 2.41198148,
       1.47701309, 2.2286042 , 3.04702127, 2.70272059, 1.96145646])

In [46]:
matriz.sum(axis=2)  

AxisError: axis 2 is out of bounds for array of dimension 2

In [54]:
cubo.sum(axis=2)  # suma por columnas

array([[0.90905916, 1.47062987, 1.93456877],
       [0.81196984, 0.16768233, 0.50916887],
       [0.35591831, 0.35491339, 0.83623164]])

In [57]:
matriz[:, 2].sum()  # suma de la tercera columna

5.679619445773227

In [59]:
matriz[0].sum()

1.5715941405256213

In [60]:
tensor.shape

(2, 3, 4, 5)

In [62]:
tensor.sum(axis=0).shape   # suma por cubos

(3, 4, 5)

In [63]:
tensor.sum(axis=1).shape   # suma por capas

(2, 4, 5)

In [65]:
tensor.sum(axis=2).shape   # suma por filas

(2, 3, 5)

In [66]:
tensor.sum(axis=3).shape   # suma por columnas

(2, 3, 4)

In [67]:
tensor.sum(axis=3)

array([[[2.21006873, 2.40077699, 2.87648023, 2.43972772],
        [2.10833914, 2.89873719, 3.10198324, 1.7650146 ],
        [2.76462468, 3.36108812, 2.8711429 , 2.06972896]],

       [[2.56028986, 3.02608772, 2.65320163, 2.35201453],
        [1.93053557, 3.46479509, 2.65181743, 2.75928188],
        [2.25130718, 3.16631943, 2.82827539, 3.09808333]]])

In [68]:
matriz.min()

0.02495849649406634

In [69]:
matriz.max()

0.9867872511864524

In [70]:
matriz[0:2, 0:2]    # Aij : matriz[filas, columnas]

array([[0.05548937, 0.03643071],
       [0.0249585 , 0.50004516]])

In [71]:
matriz[0:2, 0:2].max()

0.5000451628189772

In [72]:
matriz.max(axis=0)

array([0.98678725, 0.85323823, 0.98093764, 0.96449667])

In [73]:
matriz.max(axis=1)

array([0.98093764, 0.77989589, 0.70468915, 0.96449667, 0.97337516,
       0.68564775, 0.98678725, 0.92933064, 0.90683985, 0.72005348])

In [74]:
matriz.max()

0.9867872511864524

In [75]:
# calculo del max


lst = [54,6, 445646456, 7,8,8,6,5,4,3,5,6,6,6,6,6,7,7777]



def maximo(lst):
    
    el_maximo = 0
    
    for e in lst:
        
        if e>el_maximo:
            el_maximo=e
            
    return el_maximo


maximo(lst)

445646456

In [76]:
max(lst)

445646456

In [78]:
%%time

lst = [1,2, 3, 4]

[e+2 for e in  lst]

CPU times: user 87 µs, sys: 3 µs, total: 90 µs
Wall time: 96.1 µs


[3, 4, 5, 6]

In [80]:
%%time

np.array(lst) + 2   # vectorizado

CPU times: user 56 µs, sys: 2 µs, total: 58 µs
Wall time: 65.1 µs


array([3, 4, 5, 6])

In [81]:
matriz.mean()

0.5305730922017385

In [82]:
matriz.mean(axis=0)

array([0.48634377, 0.43665491, 0.56796194, 0.63133174])

In [83]:
matriz.std()

0.30578058468403435

In [84]:
matriz.var()

0.09350176596970991

In [85]:
matriz.var() ** 0.5

0.30578058468403435

In [86]:
matriz.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [87]:
np.median(matriz)

0.5152529415275992

In [88]:
matriz[0:8:2, 0:2]  # matriz[filas_ini:filas_final:filas_step, columnas...]

array([[0.05548937, 0.03643071],
       [0.18579632, 0.19304679],
       [0.97337516, 0.11340629],
       [0.98678725, 0.61358413]])

In [92]:
np.add(matriz[0], matriz[1])   # suma de vectores

array([0.08044787, 0.53647588, 1.63583135, 1.2786323 ])

In [93]:
np.subtract(matriz[0], matriz[1])   # resta de vectores

array([ 0.03053088, -0.46361445,  0.32604393, -0.28115947])

In [94]:
np.multiply(matriz[0], matriz[1])   # multiplicacion elemento a elemento

array([0.00138493, 0.018217  , 0.64240989, 0.38896248])

In [95]:
np.dot(matriz[0], matriz[1])   # multiplicacion escalar

1.0509743031689054

In [98]:
matriz.shape

(10, 4)

In [101]:
%%time

np.dot(matriz.T, matriz)    # producto de matrices

CPU times: user 31 µs, sys: 6 µs, total: 37 µs
Wall time: 37.9 µs


array([[3.64622029, 2.34125101, 2.21717002, 3.00312172],
       [2.34125101, 2.7604053 , 2.24963659, 3.00136092],
       [2.21717002, 2.24963659, 3.89076897, 3.39646647],
       [3.00312172, 3.00136092, 3.39646647, 4.70298832]])

In [102]:
%%time

np.matmul(matriz.T, matriz)    # producto de matrices, mas eficiente

CPU times: user 60 µs, sys: 6 µs, total: 66 µs
Wall time: 73.2 µs


array([[3.64622029, 2.34125101, 2.21717002, 3.00312172],
       [2.34125101, 2.7604053 , 2.24963659, 3.00136092],
       [2.21717002, 2.24963659, 3.89076897, 3.39646647],
       [3.00312172, 3.00136092, 3.39646647, 4.70298832]])

In [103]:
matriz.shape

(10, 4)

In [104]:
matriz.T.shape

(4, 10)

In [105]:
matriz.transpose().shape

(4, 10)

In [107]:
matriz[0] - matriz[0]   # resta de vectores

array([0., 0., 0., 0.])

In [109]:
matriz[0] + matriz[0]   # suma de vectores

array([0.11097874, 0.07286142, 1.96187528, 0.99747283])

In [111]:
np.cross(matriz[0][:3], matriz[1][:3])

array([-0.46665488, -0.01185691,  0.02683794])

In [110]:
matriz[0][:3]

array([0.05548937, 0.03643071, 0.98093764])

In [112]:
np.tensordot(matriz, matriz)

array(15.00038289)

In [113]:
matriz

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642],
       [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
       [0.18579632, 0.19304679, 0.70468915, 0.49778457],
       [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
       [0.97337516, 0.11340629, 0.38642154, 0.93877849],
       [0.27447261, 0.18394873, 0.68564775, 0.33294399],
       [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
       [0.37077889, 0.85323823, 0.92933064, 0.89367351],
       [0.90683985, 0.76705262, 0.30157504, 0.72725307],
       [0.72005348, 0.30712978, 0.35229047, 0.58198273]])

In [114]:
matriz.cumsum()   # suma acumulada

array([ 0.05548937,  0.09192008,  1.07285772,  1.57159414,  1.59655264,
        2.0965978 ,  2.75149151,  3.5313874 ,  3.71718372,  3.91023051,
        4.61491966,  5.11270423,  5.47759053,  6.27625714,  6.42962993,
        7.3941266 ,  8.36750176,  8.48090805,  8.86732959,  9.80610808,
       10.08058069, 10.26452943, 10.95017718, 11.28312117, 12.26990842,
       12.88349255, 13.41395327, 13.51172537, 13.88250426, 14.73574249,
       15.66507313, 16.55874664, 17.46558649, 18.23263912, 18.53421416,
       19.26146723, 19.98152071, 20.28865049, 20.64094096, 21.22292369])

In [115]:
matriz.cumprod()   # producto acumulada

array([5.54893725e-02, 2.02151737e-03, 1.98298248e-03, 9.88985575e-04,
       2.46835930e-05, 1.23429113e-05, 8.08329497e-06, 6.30412850e-06,
       1.17128387e-06, 2.26112590e-07, 1.59339089e-07, 7.93165403e-08,
       2.89415186e-08, 2.31146248e-08, 3.54515444e-09, 3.41928965e-09,
       3.32825160e-09, 3.77444673e-10, 1.45852752e-10, 1.36923426e-10,
       3.75817309e-11, 6.91311177e-12, 4.73995953e-12, 1.57814106e-12,
       1.55728948e-12, 9.55528105e-13, 5.06870127e-13, 4.95577568e-14,
       1.83749700e-14, 1.56782269e-14, 1.45702566e-14, 1.30210524e-14,
       1.18080093e-14, 9.05736447e-15, 2.73147507e-15, 1.98647362e-15,
       1.43036724e-15, 4.39308382e-16, 1.54764154e-16, 9.00700656e-17])

In [116]:
1e2

100.0

In [117]:
1e-2

0.01

In [118]:
np.inf

inf

In [119]:
type(np.inf)

float

In [120]:
np.nan    # nan = not a number

nan

In [121]:
type(np.nan)

float

In [122]:
np.pi

3.141592653589793

In [123]:
np.exp

<ufunc 'exp'>

In [124]:
np.exp(8)

2980.9579870417283

In [125]:
np.log

<ufunc 'log'>

In [127]:
np.cos

<ufunc 'cos'>

**Dimensiones**

In [128]:
matriz.shape

(10, 4)

In [129]:
matriz

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642],
       [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
       [0.18579632, 0.19304679, 0.70468915, 0.49778457],
       [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
       [0.97337516, 0.11340629, 0.38642154, 0.93877849],
       [0.27447261, 0.18394873, 0.68564775, 0.33294399],
       [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
       [0.37077889, 0.85323823, 0.92933064, 0.89367351],
       [0.90683985, 0.76705262, 0.30157504, 0.72725307],
       [0.72005348, 0.30712978, 0.35229047, 0.58198273]])

In [130]:
matriz.reshape((5, 8))

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642, 0.0249585 ,
        0.50004516, 0.65489371, 0.77989589],
       [0.18579632, 0.19304679, 0.70468915, 0.49778457, 0.3648863 ,
        0.79866662, 0.15337279, 0.96449667],
       [0.97337516, 0.11340629, 0.38642154, 0.93877849, 0.27447261,
        0.18394873, 0.68564775, 0.33294399],
       [0.98678725, 0.61358413, 0.53046072, 0.0977721 , 0.37077889,
        0.85323823, 0.92933064, 0.89367351],
       [0.90683985, 0.76705262, 0.30157504, 0.72725307, 0.72005348,
        0.30712978, 0.35229047, 0.58198273]])

In [131]:
matriz.reshape((8, 5))

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642, 0.0249585 ],
       [0.50004516, 0.65489371, 0.77989589, 0.18579632, 0.19304679],
       [0.70468915, 0.49778457, 0.3648863 , 0.79866662, 0.15337279],
       [0.96449667, 0.97337516, 0.11340629, 0.38642154, 0.93877849],
       [0.27447261, 0.18394873, 0.68564775, 0.33294399, 0.98678725],
       [0.61358413, 0.53046072, 0.0977721 , 0.37077889, 0.85323823],
       [0.92933064, 0.89367351, 0.90683985, 0.76705262, 0.30157504],
       [0.72725307, 0.72005348, 0.30712978, 0.35229047, 0.58198273]])

In [132]:
matriz.reshape((5, 4, 2))

array([[[0.05548937, 0.03643071],
        [0.98093764, 0.49873642],
        [0.0249585 , 0.50004516],
        [0.65489371, 0.77989589]],

       [[0.18579632, 0.19304679],
        [0.70468915, 0.49778457],
        [0.3648863 , 0.79866662],
        [0.15337279, 0.96449667]],

       [[0.97337516, 0.11340629],
        [0.38642154, 0.93877849],
        [0.27447261, 0.18394873],
        [0.68564775, 0.33294399]],

       [[0.98678725, 0.61358413],
        [0.53046072, 0.0977721 ],
        [0.37077889, 0.85323823],
        [0.92933064, 0.89367351]],

       [[0.90683985, 0.76705262],
        [0.30157504, 0.72725307],
        [0.72005348, 0.30712978],
        [0.35229047, 0.58198273]]])

In [134]:
matriz.flatten().shape

(40,)

In [135]:
cubo.flatten().shape

(18,)

In [136]:
tensor.flatten().shape

(120,)

In [137]:
np.stack((matriz, matriz))

array([[[0.05548937, 0.03643071, 0.98093764, 0.49873642],
        [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
        [0.18579632, 0.19304679, 0.70468915, 0.49778457],
        [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
        [0.97337516, 0.11340629, 0.38642154, 0.93877849],
        [0.27447261, 0.18394873, 0.68564775, 0.33294399],
        [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
        [0.37077889, 0.85323823, 0.92933064, 0.89367351],
        [0.90683985, 0.76705262, 0.30157504, 0.72725307],
        [0.72005348, 0.30712978, 0.35229047, 0.58198273]],

       [[0.05548937, 0.03643071, 0.98093764, 0.49873642],
        [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
        [0.18579632, 0.19304679, 0.70468915, 0.49778457],
        [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
        [0.97337516, 0.11340629, 0.38642154, 0.93877849],
        [0.27447261, 0.18394873, 0.68564775, 0.33294399],
        [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
        [0.3

In [138]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [139]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [140]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [141]:
np.where    # condicional

<function numpy.where>

In [142]:
matriz

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642],
       [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
       [0.18579632, 0.19304679, 0.70468915, 0.49778457],
       [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
       [0.97337516, 0.11340629, 0.38642154, 0.93877849],
       [0.27447261, 0.18394873, 0.68564775, 0.33294399],
       [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
       [0.37077889, 0.85323823, 0.92933064, 0.89367351],
       [0.90683985, 0.76705262, 0.30157504, 0.72725307],
       [0.72005348, 0.30712978, 0.35229047, 0.58198273]])

In [143]:
np.where(matriz>0.5, 1, 0)    # condicion, me das un 1, else 0

array([[0, 0, 1, 0],
       [0, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1]])

In [144]:
np.where(matriz>0.5, 1, np.where(matriz < 0.5, 2, 0))

array([[2, 2, 1, 2],
       [2, 1, 1, 1],
       [2, 2, 1, 2],
       [2, 1, 2, 1],
       [1, 2, 2, 1],
       [2, 2, 1, 2],
       [1, 1, 1, 2],
       [2, 1, 1, 1],
       [1, 1, 2, 1],
       [1, 2, 2, 1]])

In [145]:
matriz

array([[0.05548937, 0.03643071, 0.98093764, 0.49873642],
       [0.0249585 , 0.50004516, 0.65489371, 0.77989589],
       [0.18579632, 0.19304679, 0.70468915, 0.49778457],
       [0.3648863 , 0.79866662, 0.15337279, 0.96449667],
       [0.97337516, 0.11340629, 0.38642154, 0.93877849],
       [0.27447261, 0.18394873, 0.68564775, 0.33294399],
       [0.98678725, 0.61358413, 0.53046072, 0.0977721 ],
       [0.37077889, 0.85323823, 0.92933064, 0.89367351],
       [0.90683985, 0.76705262, 0.30157504, 0.72725307],
       [0.72005348, 0.30712978, 0.35229047, 0.58198273]])

In [146]:
lst = [1,2,3,54]

np.array(lst)

array([ 1,  2,  3, 54])

In [147]:
cubo = np.random.random((2, 3, 4))

cubo

array([[[0.31117901, 0.627811  , 0.97737465, 0.11554315],
        [0.52311454, 0.29868683, 0.589438  , 0.18503191],
        [0.51426306, 0.61178647, 0.75238805, 0.77948246]],

       [[0.94855128, 0.23698876, 0.96826072, 0.41813142],
        [0.29094341, 0.78010386, 0.28110811, 0.88300083],
        [0.65790665, 0.10229364, 0.53531915, 0.22773073]]])

In [148]:
cubo.shape

(2, 3, 4)

In [149]:
cubo.T

array([[[0.31117901, 0.94855128],
        [0.52311454, 0.29094341],
        [0.51426306, 0.65790665]],

       [[0.627811  , 0.23698876],
        [0.29868683, 0.78010386],
        [0.61178647, 0.10229364]],

       [[0.97737465, 0.96826072],
        [0.589438  , 0.28110811],
        [0.75238805, 0.53531915]],

       [[0.11554315, 0.41813142],
        [0.18503191, 0.88300083],
        [0.77948246, 0.22773073]]])

In [150]:
cubo.T.shape

(4, 3, 2)

In [158]:
help(cubo.transpose)

Help on built-in function transpose:

transpose(...) method of numpy.ndarray instance
    a.transpose(*axes)
    
    Returns a view of the array with axes transposed.
    
    For a 1-D array this has no effect, as a transposed vector is simply the
    same vector. To convert a 1-D array into a 2D column vector, an additional
    dimension must be added. `np.atleast2d(a).T` achieves this, as does
    `a[:, np.newaxis]`.
    For a 2-D array, this is a standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided and
    ``a.shape = (i[0], i[1], ... i[n-2], i[n-1])``, then
    ``a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0])``.
    
    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints
    
     * None or no argument: reverses the order of the axes.
    
     * tuple of ints: `i` in the `j`-th place in the tuple means `a`'s
       `i`-th axis becomes `a.transpos

In [167]:
cubo.transpose()

array([[[0.31117901, 0.94855128],
        [0.52311454, 0.29094341],
        [0.51426306, 0.65790665]],

       [[0.627811  , 0.23698876],
        [0.29868683, 0.78010386],
        [0.61178647, 0.10229364]],

       [[0.97737465, 0.96826072],
        [0.589438  , 0.28110811],
        [0.75238805, 0.53531915]],

       [[0.11554315, 0.41813142],
        [0.18503191, 0.88300083],
        [0.77948246, 0.22773073]]])

In [168]:
a = np.array([[1, 2], [3, 4]])

a

array([[1, 2],
       [3, 4]])

In [169]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [171]:
a.transpose((0, 1))

array([[1, 2],
       [3, 4]])

In [178]:
cubo.transpose((1, 0, 2)).shape   #  (1, 0, 2) son indices

(3, 2, 4)

In [179]:
cubo.transpose((2, 1, 0)).shape   # (2, 1, 0) son indices

(4, 3, 2)

In [180]:
cubo.T.shape 

(4, 3, 2)

In [181]:
cubo.transpose((2, 0, 1)).shape 

(4, 2, 3)

In [182]:
cubo

array([[[0.31117901, 0.627811  , 0.97737465, 0.11554315],
        [0.52311454, 0.29868683, 0.589438  , 0.18503191],
        [0.51426306, 0.61178647, 0.75238805, 0.77948246]],

       [[0.94855128, 0.23698876, 0.96826072, 0.41813142],
        [0.29094341, 0.78010386, 0.28110811, 0.88300083],
        [0.65790665, 0.10229364, 0.53531915, 0.22773073]]])

In [183]:
cubo.T

array([[[0.31117901, 0.94855128],
        [0.52311454, 0.29094341],
        [0.51426306, 0.65790665]],

       [[0.627811  , 0.23698876],
        [0.29868683, 0.78010386],
        [0.61178647, 0.10229364]],

       [[0.97737465, 0.96826072],
        [0.589438  , 0.28110811],
        [0.75238805, 0.53531915]],

       [[0.11554315, 0.41813142],
        [0.18503191, 0.88300083],
        [0.77948246, 0.22773073]]])

In [184]:
type(None)

NoneType