## 1) np.where

In [1]:
import numpy as np

In [2]:
array = np.random.random((5, 5))

array

array([[0.70902061, 0.20102981, 0.18438814, 0.12168688, 0.55115889],
       [0.41730123, 0.8435647 , 0.22127533, 0.91033085, 0.79328978],
       [0.36347631, 0.47486645, 0.82572069, 0.11957257, 0.51272274],
       [0.56668116, 0.6033218 , 0.85901053, 0.98668776, 0.91044724],
       [0.20533743, 0.21186401, 0.00509376, 0.12382179, 0.75233479]])

In [3]:
# np.where es un condicional
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x an

In [5]:
# donde el array valga menos de 0.5 me pones un 1, de otra manera (else) me pones un 0

np.where(array < 0.5, 1, 0)

array([[0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0]])

In [6]:
np.where(array < 0.5, 1, np.where(array < 0.8, 2, 0))   # if elif else

array([[2, 1, 1, 1, 2],
       [1, 0, 1, 0, 2],
       [1, 1, 0, 1, 2],
       [2, 2, 0, 0, 0],
       [1, 1, 1, 1, 2]])

In [7]:
array = np.array(['pikachu', 'vulvashur', 'square'])


np.where(array=='pikachu', 'hola', 0)

array(['hola', '0', '0'], dtype='<U21')

In [9]:
np.where(array=='pikachu', 'hola', 
         np.where(array=='vulvashur', 'adios', 
                  np.where(array=='square', 'hasta luegui', None)))

array(['hola', 'adios', 'hasta luegui'], dtype=object)

## 2) one-hot (aka get_dummies)

In [10]:
import pandas as pd

In [12]:
df = pd.read_excel('../data/Online Retail.xlsx')

In [13]:
df.head()

InvoiceNo         InvoiceDate StockCode  \
0     536365 2010-12-01 08:26:00    85123A   
1     536373 2010-12-01 09:02:00    85123A   
2     536375 2010-12-01 09:32:00    85123A   
3     536390 2010-12-01 10:19:00    85123A   
4     536394 2010-12-01 10:39:00    85123A   

                          Description  Quantity  UnitPrice  Revenue  \
0  CREAM HANGING HEART T-LIGHT HOLDER         6       2.55     15.3   
1  CREAM HANGING HEART T-LIGHT HOLDER         6       2.55     15.3   
2  CREAM HANGING HEART T-LIGHT HOLDER         6       2.55     15.3   
3  CREAM HANGING HEART T-LIGHT HOLDER        64       2.55    163.2   
4  CREAM HANGING HEART T-LIGHT HOLDER        32       2.55     81.6   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17511  United Kingdom  
4       13408  United Kingdom

In [15]:
df.Country.unique().shape

(35,)

In [16]:
df.Country.unique()

array(['United Kingdom', 'Spain', 'Cyprus', 'EIRE', 'Portugal',
       'Netherlands', 'Australia', 'Singapore', 'Switzerland', 'Finland',
       'Channel Islands', 'France', 'Malta', 'Italy', 'Israel', 'Germany',
       'Austria', 'Norway', 'Denmark', 'Sweden', 'Belgium', 'Canada',
       'Poland', 'Japan', 'Iceland', 'Greece', 'Lebanon', 'South Africa',
       'Czech Republic', 'USA', 'Brazil', 'United Arab Emirates',
       'Lithuania', 'Saudi Arabia', 'Bahrain'], dtype=object)

In [18]:
#help(pd.get_dummies)

In [22]:
dummie = pd.get_dummies(df, columns=['Country'])

In [24]:
#dummie.corr()

## 3) Colinealidad - Correlacion

In [27]:
#dummie.corr(numeric_only=True)

## 4) Uso de corchetes en Pandas   11) Estructuras de datos

In [31]:
df['Country'].head()

0    United Kingdom
1    United Kingdom
2    United Kingdom
3    United Kingdom
4    United Kingdom
Name: Country, dtype: object

In [33]:
type(df['Country'])

pandas.core.series.Series

In [36]:
type(df[['Country']])

pandas.core.frame.DataFrame

In [39]:
df[['Country']].head()

Country
0  United Kingdom
1  United Kingdom
2  United Kingdom
3  United Kingdom
4  United Kingdom

In [41]:
df[['Country', 'Revenue']].head()

Country  Revenue
0  United Kingdom     15.3
1  United Kingdom     15.3
2  United Kingdom     15.3
3  United Kingdom    163.2
4  United Kingdom     81.6

In [42]:
cols = ['Country', 'Revenue']

df[cols].head()

Country  Revenue
0  United Kingdom     15.3
1  United Kingdom     15.3
2  United Kingdom     15.3
3  United Kingdom    163.2
4  United Kingdom     81.6

In [47]:
df[cols][df['Revenue']>50].head()

Country  Revenue
3   United Kingdom    163.2
4   United Kingdom     81.6
10  United Kingdom     94.4
11  United Kingdom    326.4
12  United Kingdom    326.4

In [48]:
df[['Country', 'Revenue']][df['Revenue']>50].head()

Country  Revenue
3   United Kingdom    163.2
4   United Kingdom     81.6
10  United Kingdom     94.4
11  United Kingdom    326.4
12  United Kingdom    326.4

In [51]:
df[df.Revenue>10000]

InvoiceNo         InvoiceDate StockCode  \
65741     556444 2011-06-10 15:28:00     22502   

                          Description  Quantity  UnitPrice  Revenue  \
65741  PICNIC BASKET WICKER 60 PIECES        60      649.5  38970.0   

       CustomerID         Country  
65741       15098  United Kingdom

In [54]:
df.head()

InvoiceNo         InvoiceDate StockCode  \
0     536365 2010-12-01 08:26:00    85123A   
1     536373 2010-12-01 09:02:00    85123A   
2     536375 2010-12-01 09:32:00    85123A   
3     536390 2010-12-01 10:19:00    85123A   
4     536394 2010-12-01 10:39:00    85123A   

                          Description  Quantity  UnitPrice  Revenue  \
0  CREAM HANGING HEART T-LIGHT HOLDER         6       2.55     15.3   
1  CREAM HANGING HEART T-LIGHT HOLDER         6       2.55     15.3   
2  CREAM HANGING HEART T-LIGHT HOLDER         6       2.55     15.3   
3  CREAM HANGING HEART T-LIGHT HOLDER        64       2.55    163.2   
4  CREAM HANGING HEART T-LIGHT HOLDER        32       2.55     81.6   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17511  United Kingdom  
4       13408  United Kingdom

## 5) datetime

In [58]:
type(df.InvoiceDate[0])

pandas._libs.tslibs.timestamps.Timestamp

In [60]:
str(df.InvoiceDate[0])

'2010-12-01 08:26:00'

In [62]:
#help(df.InvoiceDate[0])

In [71]:
df.InvoiceDate[0].weekday()

2

In [72]:
df.InvoiceDate[0].day_name()

'Wednesday'

## 6) sobreescribe pedazo del df

In [76]:
indice = df[df.Country=='United Kingdom'].index

In [79]:
df.loc[indice, 'Quantity'] = -1

In [81]:
df.loc[indice].head()

InvoiceNo         InvoiceDate StockCode  \
0     536365 2010-12-01 08:26:00    85123A   
1     536373 2010-12-01 09:02:00    85123A   
2     536375 2010-12-01 09:32:00    85123A   
3     536390 2010-12-01 10:19:00    85123A   
4     536394 2010-12-01 10:39:00    85123A   

                          Description  Quantity  UnitPrice  Revenue  \
0  CREAM HANGING HEART T-LIGHT HOLDER        -1       2.55     15.3   
1  CREAM HANGING HEART T-LIGHT HOLDER        -1       2.55     15.3   
2  CREAM HANGING HEART T-LIGHT HOLDER        -1       2.55     15.3   
3  CREAM HANGING HEART T-LIGHT HOLDER        -1       2.55    163.2   
4  CREAM HANGING HEART T-LIGHT HOLDER        -1       2.55     81.6   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17511  United Kingdom  
4       13408  United Kingdom

In [84]:
df.Quantity.unique()

array([  -1,    1,   64,   24,    6,  256,   18,   32,    8,   36,   12,
          9,    2,   72,   30,   60,    4,   96,   10,  160,   16,    3,
        128,   48,  120,   40,  144,   20,   11,  204,   50,  200,  100,
        192,  240,    5,  384,  320,  640,  448,  300,  288,   84,  432,
        480,  576,  108,  216, 1152,   15,  504,  360,   44,   70,   80,
        180, 1440, 1200,  156,   21,   33,   28,  400,  500,  150,   90,
         47,   25,   14,  720, 1488,  336,  960,    7, 1728,   56,  117,
         43,   92,   75,  125,  408,   45,   94,  264,  176,  168,  768,
        600,   54,   34,   19,  250,  272,  407,   17,   42,   13, 2400,
        912, 2040,  140])

In [87]:
donde_el_menos_uno = df[df['Quantity']==-1].index

df.loc[donde_el_menos_uno, 'Quantity'] = 'hola'

In [88]:
df.head()

InvoiceNo         InvoiceDate StockCode  \
0     536365 2010-12-01 08:26:00    85123A   
1     536373 2010-12-01 09:02:00    85123A   
2     536375 2010-12-01 09:32:00    85123A   
3     536390 2010-12-01 10:19:00    85123A   
4     536394 2010-12-01 10:39:00    85123A   

                          Description Quantity  UnitPrice  Revenue  \
0  CREAM HANGING HEART T-LIGHT HOLDER     hola       2.55     15.3   
1  CREAM HANGING HEART T-LIGHT HOLDER     hola       2.55     15.3   
2  CREAM HANGING HEART T-LIGHT HOLDER     hola       2.55     15.3   
3  CREAM HANGING HEART T-LIGHT HOLDER     hola       2.55    163.2   
4  CREAM HANGING HEART T-LIGHT HOLDER     hola       2.55     81.6   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17511  United Kingdom  
4       13408  United Kingdom

## 7) Drop Filas

In [90]:
donde_el_menos_uno[:5]

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [97]:
df.drop(donde_el_menos_uno, axis=0, inplace=True)

In [99]:
df.head()

InvoiceNo         InvoiceDate StockCode  \
103     538095 2010-12-09 14:55:00    85123A   
147     538826 2010-12-14 12:58:00    85123A   
179     539320 2010-12-16 19:16:00    85123A   
183     539353 2010-12-17 11:30:00    85123A   
198     539722 2010-12-21 13:45:00    85123A   

                            Description Quantity  UnitPrice  Revenue  \
103  CREAM HANGING HEART T-LIGHT HOLDER        1       2.95     2.95   
147  CREAM HANGING HEART T-LIGHT HOLDER       64       2.55   163.20   
179  CREAM HANGING HEART T-LIGHT HOLDER       24       2.95    70.80   
183  CREAM HANGING HEART T-LIGHT HOLDER        6       2.95    17.70   
198  CREAM HANGING HEART T-LIGHT HOLDER       24       2.95    70.80   

     CustomerID   Country  
103       17097     Spain  
147       12370    Cyprus  
179       14911      EIRE  
183       12782  Portugal  
198       14911      EIRE

## 8) Generadores

In [100]:
(i for i in range(8))

<generator object <genexpr> at 0x169b47c80>

In [101]:
gen = (i for i in range(8))

In [102]:
gen

<generator object <genexpr> at 0x169b47200>

In [103]:
next(gen)

0

In [104]:
next(gen)

1

In [105]:
list(gen)

[2, 3, 4, 5, 6, 7]

In [106]:
next(gen)

StopIteration: 

In [107]:
gen

<generator object <genexpr> at 0x169b47200>

In [108]:
def funcion():
    return 2

In [109]:
def generador():
    yield 2

In [111]:
funcion()

2

In [112]:
generador()

<generator object generador at 0x16c20e5f0>

In [113]:
gen = generador()

In [114]:
next(gen)

2

In [115]:
next(gen)

StopIteration: 

In [118]:
gen = (i for i in range(8))

lista = list(gen)

In [119]:
next(gen)

StopIteration: 

In [120]:
lista

[0, 1, 2, 3, 4, 5, 6, 7]

In [121]:
[i for i in range(8)]

[0, 1, 2, 3, 4, 5, 6, 7]

## 9) Filtrar un df (hecho)

## 10) apply a un df

In [129]:
df.UnitPrice ** 2

103       8.7025
147       6.5025
179       8.7025
183       8.7025
198       8.7025
           ...  
396001    8.3521
396005    6.2001
396007    8.3521
396021    6.2001
396022    8.3521
Name: UnitPrice, Length: 42051, dtype: float64

In [128]:
df[['UnitPrice', 'Revenue']].apply(lambda x: x**2)

UnitPrice     Revenue
103        8.7025      8.7025
147        6.5025  26634.2400
179        8.7025   5012.6400
183        8.7025    313.2900
198        8.7025   5012.6400
...           ...         ...
396001     8.3521    300.6756
396005     6.2001  22320.3600
396007     8.3521   1202.7024
396021     6.2001  22320.3600
396022     8.3521   1202.7024

[42051 rows x 2 columns]

In [127]:
df[['UnitPrice', 'Revenue']].apply(lambda x: x.apply(lambda y: y**2))

UnitPrice     Revenue
103        8.7025      8.7025
147        6.5025  26634.2400
179        8.7025   5012.6400
183        8.7025    313.2900
198        8.7025   5012.6400
...           ...         ...
396001     8.3521    300.6756
396005     6.2001  22320.3600
396007     8.3521   1202.7024
396021     6.2001  22320.3600
396022     8.3521   1202.7024

[42051 rows x 2 columns]

In [133]:
df['nueva'] = df['UnitPrice'] * df['Quantity']

df.head()

InvoiceNo         InvoiceDate StockCode  \
103     538095 2010-12-09 14:55:00    85123A   
147     538826 2010-12-14 12:58:00    85123A   
179     539320 2010-12-16 19:16:00    85123A   
183     539353 2010-12-17 11:30:00    85123A   
198     539722 2010-12-21 13:45:00    85123A   

                            Description Quantity  UnitPrice  Revenue  \
103  CREAM HANGING HEART T-LIGHT HOLDER        1       2.95     2.95   
147  CREAM HANGING HEART T-LIGHT HOLDER       64       2.55   163.20   
179  CREAM HANGING HEART T-LIGHT HOLDER       24       2.95    70.80   
183  CREAM HANGING HEART T-LIGHT HOLDER        6       2.95    17.70   
198  CREAM HANGING HEART T-LIGHT HOLDER       24       2.95    70.80   

     CustomerID   Country  nueva  
103       17097     Spain   2.95  
147       12370    Cyprus  163.2  
179       14911      EIRE   70.8  
183       12782  Portugal   17.7  
198       14911      EIRE   70.8

In [137]:
df[df.columns.sort_values()]

Country  CustomerID                          Description  \
103           Spain       17097   CREAM HANGING HEART T-LIGHT HOLDER   
147          Cyprus       12370   CREAM HANGING HEART T-LIGHT HOLDER   
179            EIRE       14911   CREAM HANGING HEART T-LIGHT HOLDER   
183        Portugal       12782   CREAM HANGING HEART T-LIGHT HOLDER   
198            EIRE       14911   CREAM HANGING HEART T-LIGHT HOLDER   
...             ...         ...                                  ...   
396001       France       12583  SET OF 6 RIBBONS PERFECTLY PRETTY     
396005  Netherlands       14646  SET OF 6 RIBBONS PERFECTLY PRETTY     
396007      Germany       12621  SET OF 6 RIBBONS PERFECTLY PRETTY     
396021  Netherlands       14646               SET OF 6 RIBBONS PARTY   
396022      Germany       12621               SET OF 6 RIBBONS PARTY   

               InvoiceDate  InvoiceNo Quantity  Revenue StockCode  UnitPrice  \
103    2010-12-09 14:55:00     538095        1     2.95    85123A       2.95   
147    2010-12-14 12:58:00     538826       64   163.20    85123A       2.55   
179    2010-12-16 19:16:00     539320       24    70.80    85123A       2.95   
183    2010-12-17 11:30:00     539353        6    17.70    85123A       2.95   
198    2010-12-21 13:45:00     539722       24    70.80    85123A       2.95   
...                    ...        ...      ...      ...       ...        ...   
396001 2011-12-07 08:07:00     581001        6    17.34     23562       2.89   
396005 2011-12-07 15:16:00     581175       60   149.40     23562       2.49   
396007 2011-12-08 11:25:00     581266       12    34.68     23562       2.89   
396021 2011-12-07 15:16:00     581175       60   149.40     23561       2.49   
396022 2011-12-08 11:25:00     581266       12    34.68     23561       2.89   

        nueva  
103      2.95  
147     163.2  
179      70.8  
183      17.7  
198      70.8  
...       ...  
396001  17.34  
396005  149.4  
396007  34.68  
396021  149.4  
396022  34.68  

[42051 rows x 10 columns]

## 13) lambda

In [138]:
def nombre(param, param2):
    
    return param**param2

In [139]:
nombre(8, 9)

134217728

In [140]:
lambda param, param2: param**param2

<function __main__.<lambda>(param, param2)>

In [141]:
nombre

<function __main__.nombre(param, param2)>

In [142]:
n = lambda param, param2: param**param2

n

<function __main__.<lambda>(param, param2)>

In [143]:
n(87, 9)

285544154243029527

In [144]:
lambda param, param2: [param*e for e in range(param2)]

<function __main__.<lambda>(param, param2)>

In [145]:
n = lambda param, param2: [param*e for e in range(param2)]

n(3, 4)

[0, 3, 6, 9]

In [149]:
df.Quantity.apply(lambda x: x**4).head()

103           1
147    16777216
179      331776
183        1296
198      331776
Name: Quantity, dtype: int64

## 14) Func vs OOP

In [150]:
def restar(a, b):
    return a-b

In [151]:
array

array(['pikachu', 'vulvashur', 'square'], dtype='<U9')

In [152]:
df.head()

InvoiceNo         InvoiceDate StockCode  \
103     538095 2010-12-09 14:55:00    85123A   
147     538826 2010-12-14 12:58:00    85123A   
179     539320 2010-12-16 19:16:00    85123A   
183     539353 2010-12-17 11:30:00    85123A   
198     539722 2010-12-21 13:45:00    85123A   

                            Description Quantity  UnitPrice  Revenue  \
103  CREAM HANGING HEART T-LIGHT HOLDER        1       2.95     2.95   
147  CREAM HANGING HEART T-LIGHT HOLDER       64       2.55   163.20   
179  CREAM HANGING HEART T-LIGHT HOLDER       24       2.95    70.80   
183  CREAM HANGING HEART T-LIGHT HOLDER        6       2.95    17.70   
198  CREAM HANGING HEART T-LIGHT HOLDER       24       2.95    70.80   

     CustomerID   Country  nueva  
103       17097     Spain   2.95  
147       12370    Cyprus  163.2  
179       14911      EIRE   70.8  
183       12782  Portugal   17.7  
198       14911      EIRE   70.8

In [153]:
array.shape

(3,)

In [154]:
contador = 0


for e in array:
    contador+=1
    
contador

3

In [155]:
type(array.shape)

tuple

In [157]:
type(array)

numpy.ndarray

In [159]:
type(array.size)

int